services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - "2368:2368"
    env_file:
      - .env
    volumes:
      - ./content:/var/lib/ghost/content
      - ./content/themes/kalp-dev:/var/lib/ghost/content/themes/kalp-dev
    depends_on:
      - db

  ghost-poetry:
    image: ghost:5-alpine
    restart: always
    ports:
      - "2369:2368"
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=ghostpassword
      - database__connection__database=ghost_poetry_db
      - url=https://poetry.kalp.dev
      - NODE_ENV=production
    volumes:
      - ./poetry-content:/var/lib/ghost/content
      - ./poetry-content/themes/poetry-theme:/var/lib/ghost/content/themes/poetry-theme
    depends_on:
      - db

  ghost-blog:
    image: ghost:5-alpine
    restart: always
    ports:
      - "2370:2368"
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=ghostpassword
      - database__connection__database=ghost_blog_db
      - url=https://blog.kalp.dev
      - NODE_ENV=production
    volumes:
      - ./blog-content:/var/lib/ghost/content
      - ./blog-content/themes/blog-theme:/var/lib/ghost/content/themes/blog-theme
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql

